# Generated by Django 6.0 on 2026-06-14 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], null=True)),
                ('discipline', models.CharField(blank=True, choices=[('software_eng', 'Software Engineering'), ('cybersecurity', 'Cybersecurity'), ('data_science', 'Data Science'), ('ui_ux', 'UI/UX Design'), ('networking', 'Networking'), ('ai_ml', 'AI / Machine Learning')], max_length=20, null=True)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='universities.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
