# Generated by Django 6.0.6 on 2026-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reg_number',
            field=models.CharField(blank=True, help_text='University registration number', max_length=50, null=True),
        ),
    ]
