# Generated by Django 6.0.6 on 2026-09-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_user_type_employerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Used for notifications if different from your login email', max_length=254),
        ),
    ]
