# Generated by Django 6.0.6 on 2026-10-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio_public',
            field=models.BooleanField(default=True, help_text='If enabled, your portfolio is visible to employers and the public.'),
        ),
    ]
