# Generated by Django 6.0.6 on 2026-09-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_employerinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='expected_skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills e.g. Python, conditionals, functions'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='objective',
            field=models.TextField(blank=True, help_text='What the student should achieve'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='requirements',
            field=models.TextField(blank=True, help_text='One requirement per line'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='submission_instructions',
            field=models.TextField(blank=True, help_text='What to submit and how'),
        ),
    ]
