# Generated by Django 6.0.6 on 2026-09-20 10:16

import challenges.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_expected_skills_challenge_objective_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='github_repo_url',
        ),
        migrations.AddField(
            model_name='challenge',
            name='allows_external_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='allows_file_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='allows_github',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='allows_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='track',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware / IoT')], default='software', max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='external_url',
            field=models.URLField(blank=True, help_text='Figma, Wokwi, Tinkercad, YouTube, or other external link'),
        ),
        migrations.AddField(
            model_name='submission',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL'),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(blank=True, help_text='Score out of challenge points', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='text_answer',
            field=models.TextField(blank=True, help_text='Written answer or explanation'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='expected_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='min_year',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='submission_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=challenges.models.submission_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='challenges.submission')),
            ],
        ),
    ]
