# Generated by Django 6.0.6 on 2026-10-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_remove_submission_github_repo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='assessment_criteria',
            field=models.TextField(blank=True, help_text='What a strong submission demonstrates — visible to students before submitting and to reviewers when assessing. Be specific: what separates a pass from a fail for this challenge.'),
        ),
    ]
