# Generated by Django 6.1 on 2026-08-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='email_domain',
            field=models.CharField(blank=True, help_text='Student email domain e.g. students.uok.ac.ke', max_length=100),
        ),
    ]
